Adding accept header for definition get resource
wso2/apk pull request #1003
Opened 2023-04-10 11:39 UTC by CrowleyRajapakse

## Purpose
Adding accept header for definition get resource

2023-04-10 12:28 UTC, tharindu1st requested changes

2023-04-10 12:28 UTC, tharindu1st commented on runtime/runtime-domain-service/ballerina/APIClient.bal
> +                    if accept == "application/json" || accept == "*/*" {
use constants for media types

2023-04-10 12:28 UTC, tharindu1st commented on runtime/runtime-domain-service/ballerina/APIClient.bal
> +                    } else if accept == "application/yaml" {
same goes here

2023-04-10 13:20 UTC, CrowleyRajapakse commented on runtime/runtime-domain-service/ballerina/APIClient.bal
> +                    if accept == "application/json" || accept == "*/*" {
fixed and resolved

2023-04-10 13:20 UTC, CrowleyRajapakse commented on runtime/runtime-domain-service/ballerina/APIClient.bal
> +                    } else if accept == "application/yaml" {
fixed and resolved

2023-04-11 11:19 UTC, tharindu1st approved these changes

2023-04-11 11:20 UTC, merged