Add trace headers
wso2/apk pull request #1305
Opened 2023-06-25 14:42 UTC by PasanT9

## Purpose
> $subject

2023-06-30 08:20 UTC, tharindu1st requested changes

2023-06-30 08:21 UTC, tharindu1st commented
verify thread-local variables get cleared properly

2023-07-04 04:25 UTC, PasanT9 commented on gateway/enforcer/org.wso2.apk.enforcer/src/main/java/org/wso2/apk/enforcer/grpc/ExtAuthService.java
> +            ThreadContext.remove(APIConstants.API_UUID);
Fixed

2023-07-04 04:42 UTC, tharindu1st approved these changes

2023-07-04 05:15 UTC, merged