Add Prometheus support for API
wso2/apk pull request #2042
Opened 2024-02-29 06:29 UTC by sgayangi

## Purpose
> Adds Prometheus support for APK

2024-03-02 15:15 UTC, tharindu1st requested changes

2024-03-03 04:20 UTC, sgayangi commented on adapter/config/default_config.go
> +			Enabled:            true,
Fixed in [5a39680](https://github.com/wso2/apk/pull/2042/commits/5a3968029745721c1df2b481508a9d4783ca59c0)

2024-03-06 10:49 UTC, Krishanx92 approved these changes

2024-03-06 10:54 UTC, tharindu1st approved these changes

2024-03-06 10:54 UTC, merged